Repository kbojarowska/DoTheBeast, pull requests merged in 2023-11, with the labels that each got.

#27 added user CRUD
  backend/controllers/userController.js
  backend/index.js
  backend/models/taskModel.js
  backend/models/trophyModel.js
  backend/models/userModel.js
  backend/package-lock.json
  backend/package.json
  backend/routes/userRoutes.js
Labels: BE, feature

#25 Created landing page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.scss
  frontend/src/colors.scss
  frontend/src/components/Button/Button.js
  frontend/src/components/Button/Button.scss
  frontend/src/components/Text/Text.js
  frontend/src/components/Text/Text.scss
  frontend/src/components/index.js
  frontend/src/index.js
  frontend/src/index.scss
  frontend/src/pages/LandingPage/LandingPage.js
  frontend/src/pages/LandingPage/LandingPage.scss
Labels: FE, feature

#36 created task prioritization function
  backend/controllers/taskController.js
Labels: BE, feature

#43 Make some improvements and code cleanup
  backend/controllers/userController.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  backend/utils/generateToken.js
  backend/yarn.lock
Labels: bug

#39 22 be create to do list crud
  backend/controllers/taskController.js
  backend/controllers/todoListController.js
  backend/index.js
  backend/models/taskModel.js
  backend/models/todoListModel.js
  backend/models/userModel.js
  backend/package-lock.json
  backend/routes/taskRoutes.js
  backend/routes/todoListRoutes.js
  backend/utils/calculatePriority.js
Labels: BE

#45 44 create main page layout
  frontend/src/App.js
  frontend/src/pages/MainPage/MainPage.js
  frontend/src/pages/MainPage/MainPage.scss
Labels: FE
